### ISSUE TITLE
Why to Remove http and https Part of the link ? (In Screen Short)

### ISSUE THREAD

**Issue by hpnightowl** [Saket-Upadhyay/SAMPARK#1]
I am bit lasy and copy paste stuff so why not just add this Function for taking in that URL of website as it is then Checking it? 
```
function remove(url){
    removepart = array("http://","https://");
    return str_replace(removepart,"",url);
}
```

**Comment by Saket-Upadhyay** [comment]
Yes, that's what we want to do. As this is a prototype we didn't implement that function. Feel free to create a request and add the function.
Check [TODO](https://github.com/Saket-Upadhyay/SAMPARK/blob/master/TODO.md) list

**Comment by hpnightowl** [comment]
Ok let me see the whole repo then will PR

**Comment by hpnightowl** [comment]
https://github.com/Saket-Upadhyay/SAMPARK/pull/2 -Here Is Fix Any Changes Needed?

**Comment by Saket-Upadhyay** [comment]
Merge accepted. Let's run some tests on Heroku then will close this issue.

**Comment by Saket-Upadhyay** [comment]
The function is working.
The sanitisation was not global, so only had to movel the function call in **processurl(char \*,char \*)**

**_httpscheck.rmrf_protocol()_** now removes ("https://" and "http://" prefix)

Closing this issue. Thanks for your contribution.

_*TODO updated_
