### ISSUE TITLE
Trust List

### ISSUE THREAD

**Issue by ayush123460** [Saket-Upadhyay/SAMPARK#3]
Let's Encrypt Authority X3 is not in the trusted issuer list.

**Comment by Saket-Upadhyay** [comment]
I have not included __Let's Encrypt__ as they are free so anyone can use it also most of the known banks and payment portals don't use Let's Encrypt.

But, anyway in case you find any popular portal using it and want to add in the project feel free to create a pull request with the website URL. We will add it in this case.

**Comment by ayush123460** [comment]
Tons of websites use Let's Encrypt certificates *before* handing off to the gateway. I suggest adding in a warning note about it, instead of outright claiming it's not legit.

**Comment by Saket-Upadhyay** [comment]
Added in LetsEncrypt-inclusion branch.
